spring:

  devtools:
    livereload:
      enable: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-id: a8b117c6a83d4c470135d900ad8f48a7
            client-secret: 1jIerDMo725WOiIf1s3pOWoz84ejrlmD
            redirect-uri: "http://localhost:8080/auth/kakao/callback"
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mvc:
    static-path-pattern: /static/**



  resource:
    static-locations: classpath:/resources/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: tmdrb
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true



